---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    code_folding: hide 
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r}
data("instacart")

set.seed(1)

data(instacart)

instacart =
  instacart %>% 
  janitor::clean_names() %>%
  mutate(product_name = str_to_lower(product_name)) %>%
  select(aisle, order_dow, order_hour_of_day, product_name, aisle_id) %>%
  mutate(
    day_of_week = recode(order_dow,
                         `1` = "monday", 
                         `2` = "tuesday", 
                         `3` = "wednesday", 
                         `4` = "thursday", 
                         `5` = "friday", 
                         `6` = "saturday",
                         `0` = "sunday"),
    day_of_week = forcats::fct_relevel(day_of_week, c("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"))
  )
```

Column {data-width=500}
-----------------------------------------------------------------------

### Number of Products Sold in Aisles (>20,000) of Instacart

```{r}
x_template =
  list(title = "Aisle Name")

y_template =
  list(title = "Number of Products Ordered")

instacart %>%
  count(aisle) %>%
  filter(n > 20000) %>%
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar") %>%
  layout(
    xaxis = x_template,
    yaxis = y_template
    )
```

Column {data-width=500}
-----------------------------------------------------------------------

### Mean Hour of Day Products from the 'Fresh Vegetable' Aisle are Ordered Across the Week

```{r}
x_template =
  list(title = "Day of Week")

y_template =
  list(title = "Mean Hour of Day")

instacart %>%
  filter(aisle == "fresh vegetables") %>%
  group_by(product_name, day_of_week) %>%
  summarize(mean_hour = mean(order_hour_of_day)) %>%
  plot_ly(y = ~mean_hour, color = ~day_of_week, type = "violin", colors = "Set2")  %>%
  layout(
    xaxis = x_template,
    yaxis = y_template
    )
```
